Creato progetto API. Creati progetti di test.
JustCracco/GameFinder pull request #1
Opened 2023-06-22 13:22 UTC by JustCracco

2023-06-22 13:36 UTC, DeltaNicola requested changes

2023-06-22 13:36 UTC, DeltaNicola commented on GameFinder_WebAPInum2/Controllers/GamesController.cs
> +
```C#
if ( check != null )
    return StatusCode(StatusCodes.Status202Accepted, check);

if ( e == null )
    return BadRequest();

if ( e is ArgumentNullException )
    return BadRequest();
    
if ( e is ArgumentException )
    return Conflict();

return StatusCode(StatusCodes.Status500InternalServerError);
```

2023-06-22 14:49 UTC, treebyte-dev commented on GameFinder_WebAPInum2/Services/GameService.cs
> +                        if (games[i].name != UpdateGame.name)
aggiorna tutti i campi direttamente

2023-06-22 14:49 UTC, treebyte-dev commented on GameFinder_WebAPInum2/Services/IService/IGameService.cs
> +        public Task<(ArgumentException?, Game?)> AddGameAsync(Game NewGame);
non serve rritornare ecceezioni, ritorna sempre un valore solo, le eccezioni lanciale

2023-06-22 14:49 UTC, treebyte-dev commented on GameFinder_Tests/GameFinder_TestService.cs
> +                name = "Fallout 4",
In generale verifica i giochi che non serve aggiungere test per test

2023-06-22 14:50 UTC, treebyte-dev commented on GameFinder_WebAPInum2/Services/GameService.cs
> +                List<Game> games = await db.Games.ToListAsync();
vale qui come vale in altri posti, non chiamare questo per avere tutti i giochi ma usa .Any, .First, .Where per ottenere al minimo quello che ti serve

2023-06-26 13:37 UTC, DeltaNicola requested changes

2023-06-26 13:37 UTC, DeltaNicola commented on GameFinder_WebAPInum2/Controllers/GamesController.cs
>                  return StatusCode(StatusCodes.Status500InternalServerError, $"Gioco non trovato");
```c#
return NotFound();
```

2023-06-26 13:37 UTC, DeltaNicola commented on GameFinder_WebAPInum2/Services/GameService.cs
> +        public async Task<List<Game>> GetGameByVoteAsync(float minVote)
```c#
return Db.Games.Where(game => game.Vote >= minVote).ToList();
```

2023-06-26 13:37 UTC, DeltaNicola commented on GameFinder_WebAPInum2/Services/GameService.cs
> +        public void StartDb()
rimuovere metodo non utilizzato

2023-06-26 14:02 UTC, merged